<?php
// api_gemini.php
// 這是後端引擎，負責與 Google Gemini 溝通
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *'); // 允許跨域調用 (視伺服器設定而定)

// ==========================================
// 【設定區】請在這裡填入您的 Google Gemini API Key
$apiKey = 'AIzaSyCgdOIyEOQxPE8AbjKtDypiiTydzWxnGjM';
// ==========================================

// 接收前端傳來的 JSON 數據
$inputJSON = file_get_contents('php://input');
$input = json_decode($inputJSON, true);

// 基本檢查
if (!$input || !isset($input['message'])) {
    echo json_encode(['error' => 'No input provided']);
    exit;
}

$userMessage = $input['message'];
$history = $input['history'] ?? []; // 獲取前端傳來的對話歷史

// 1. 設定 AI 的人設 (System Instruction)
// 這裡設定 AI 為一位香港中學英語老師，並根據學生程度調整寫作風格
$systemInstruction = "You are a supportive Hong Kong secondary school English teacher. 
Your goal is to help students write a self-introduction text.
RULES:
1. If the user sends profile data, generate a structured, natural self-introduction draft.
2. If the user asks for changes (refinement), rewrite the text based on their request.
3. ALWAYS output the English text clearly.
4. If the English level is 'Junior', use simple grammar (Present Tense), short sentences, and easy vocabulary.
5. If the English level is 'Senior', use complex sentence structures (Relative clauses, Passive voice) and DSE-level vocabulary.
6. Be encouraging and helpful.";

// 2. 構建 Gemini 需要的 'contents' 結構
// Gemini 的對話格式要求非常嚴格，必須是 User -> Model -> User 的順序
$contents = [];

// 為了讓 System Instruction 生效，我們把它包裝在第一條 User Message 裡 (這是目前最穩定的做法)
// 如果沒有歷史對話，代表是第一次請求
if (empty($history)) {
    $firstMessage = $systemInstruction . "\n\n[Student Request]: " . $userMessage;
    $contents[] = [
        'role' => 'user',
        'parts' => [['text' => $firstMessage]]
    ];
} else {
    // 如果有歷史對話，先加入 System Prompt 到最開頭 (作為 context)
    // 注意：為了維持輪替順序，我們通常把 System Prompt 隱含在對話邏輯中，
    // 或者簡單地在最新的 Prompt 前面再次強調重點。
    
    // 重建歷史對話
    foreach ($history as $msg) {
        // 前端傳來的是 OpenAI 格式 (user/assistant)，轉為 Gemini 格式 (user/model)
        $role = ($msg['role'] === 'assistant') ? 'model' : 'user';
        $contents[] = [
            'role' => $role,
            'parts' => [['text' => $msg['content']]]
        ];
    }
    
    // 加入最新的使用者訊息
    $contents[] = [
        'role' => 'user',
        'parts' => [['text' => $userMessage]]
    ];
}

// 3. 準備發送給 Google API 的資料
$data = [
    "contents" => $contents,
    "generationConfig" => [
        "temperature" => 0.7,      // 創意度
        "maxOutputTokens" => 800   // 字數限制
    ]
];

// 4. 使用 cURL 發送請求
// 使用 gemini-1.5-flash 模型 (速度快、免費額度高)
$url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" . $apiKey;

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'Content-Type: application/json'
]);

$response = curl_exec($ch);
$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

if (curl_errno($ch)) {
    echo json_encode(['error' => 'Connection Error: ' . curl_error($ch)]);
    exit;
}
curl_close($ch);

// 5. 處理 Google 的回傳結果
$responseData = json_decode($response, true);

// 檢查是否有錯誤
if ($httpCode !== 200) {
    $errorMsg = $responseData['error']['message'] ?? 'Unknown API Error';
    echo json_encode(['error' => 'API Error: ' . $errorMsg]);
    exit;
}

// 提取 AI 回覆的文字
// Gemini 回傳路徑: candidates[0] -> content -> parts[0] -> text
if (isset($responseData['candidates'][0]['content']['parts'][0]['text'])) {
    $aiText = $responseData['candidates'][0]['content']['parts'][0]['text'];
    
    // 回傳給前端 (統一格式)
    echo json_encode([
        'success' => true,
        'reply' => $aiText
    ]);
} else {
    echo json_encode(['error' => 'No content generated by AI.']);
}
?>